load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "attribution",
    visibility = ["//visibility:public"],
    srcs = [
      "EnergyAttributer.java",
      "EnergyAttribution.java",
    ],
    deps = [
      "//src/main/java/chappie/profiling:core",
    ],
)
