/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stack_top */

#ifndef _Included_GLIBCLibrary
#define _Included_GLIBCLibrary
#ifdef __cplusplus
extern "C" {
#endif
  JNIEXPORT jstring JNICALL Java_chappie_util_GLIBC_getStackTraceTop(JNIEnv* nev, jobject o, jthread thread);
#ifdef __cplusplus
}
#endif
#endif
